### ISSUE TITLE
GCC-9.2.1 warnings for stubs

### ISSUE THREAD

**Issue by XVilka** [madroach/ocaml-zlib#7]
```
zlib_stubs.c: In function 'zlib_finalize':
zlib_stubs.c:100:7: warning: variable 'ret' set but not used [-Wunused-but-set-variable]
   int ret;
       ^~~
zlib_stubs.c: In function 'zlib_get_header':
zlib_stubs.c:397:11: warning: implicit declaration of function 'strnlen'; did you mean 'strlen'? [-Wimplicit-function-declaration]
     len = strnlen((char *)header->name, header->name_max);
           ^~~~~~~
           strlen
```

**Comment by madroach** [comment]
> ```
> zlib_stubs.c: In function 'zlib_finalize':
> zlib_stubs.c:100:7: warning: variable 'ret' set but not used [-Wunused-but-set-variable]
>    int ret;
>        ^~~

I believe this is fixed now.

> zlib_stubs.c: In function 'zlib_get_header':
> zlib_stubs.c:397:11: warning: implicit declaration of function 'strnlen'; did you mean 'strlen'? [-Wimplicit-function-declaration]
>      len = strnlen((char *)header->name, header->name_max);
>            ^~~~~~~
>            strlen
> ```

I don't understand this one. ``strnlen`` is declared in ``string.h``, which is included. Could you please check what ``man strnlen`` says about headers on your machine and / or grep for ``strnlen`` in your ``/usr/include``.

**Comment by XVilka** [comment]
@madroach I met this error building in Alpine Linux container, which uses [musl libc](https://www.musl-libc.org/). Here it is `strings.h` - https://git.musl-libc.org/cgit/musl/tree/include/string.h

I am not sure, may be it does not define the `_POSIX_C_SOURCE` or `_GNU_SOURCE`?
See also this stackoverflow question: https://stackoverflow.com/questions/46995050/gcc-warning-implicit-declaration-of-function-strnlen-when-dialect-c99-or-c11

I also tested with Fedora Linux 31, it shows the same, while strnlen presented too:
![image](https://user-images.githubusercontent.com/203261/70593209-217eb900-1c17-11ea-8205-e59e9e00bf33.png)

**Comment by madroach** [comment]
Hi, thanks for you insights. I added the required feature test definition Would you be so kind and test whether this issue is now fixed and then maybe close the issue?

**Comment by XVilka** [comment]
I confirm, it was fixed, thanks!
