### ISSUE TITLE
Opam-CI failure compiling on archlinux

### ISSUE THREAD

**Issue by antoinemine** [madroach/ocaml-zlib#8]
While proposing a new Opam package for our analyzer, MOPSA https://github.com/ocaml/opam-repository/pull/25897, that depends on ocaml-zlib, we noticed a failure of Opam-CI on archlinux when compiling ocaml-zlib. The problem concerns the `strnlen` function. Cf.  https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/2ef3c29649c756730ea6576e92ffc6fe6f9f3e27/variant/distributions,archlinux-ocaml-4.14,mopsa.1.0~pre4
It is probably related to #7.

**Comment by madroach** [comment]
Indeed, this has been fixed in 0a08762. Seems like it is time to do a release?

**Comment by madroach** [comment]
fixed by [0.7](https://github.com/madroach/ocaml-zlib/releases/tag/0.7)

**Comment by antoinemine** [comment]
Thanks !
